// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: stream.proto
#ifndef GRPC_stream_2eproto__INCLUDED
#define GRPC_stream_2eproto__INCLUDED

#include "stream.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace gpss {

class GreenplumStreamServer final {
 public:
  static constexpr char const* service_full_name() {
    return "gpss.GreenplumStreamServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::gpss::StreamMessages>> Consume(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::gpss::StreamMessages>>(ConsumeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::gpss::StreamMessages>> AsyncConsume(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::gpss::StreamMessages>>(AsyncConsumeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::gpss::StreamMessages>> PrepareAsyncConsume(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::gpss::StreamMessages>>(PrepareAsyncConsumeRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::gpss::StreamMessages>* ConsumeRaw(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::gpss::StreamMessages>* AsyncConsumeRaw(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::gpss::StreamMessages>* PrepareAsyncConsumeRaw(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::gpss::StreamMessages>> Consume(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::gpss::StreamMessages>>(ConsumeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::gpss::StreamMessages>> AsyncConsume(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::gpss::StreamMessages>>(AsyncConsumeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::gpss::StreamMessages>> PrepareAsyncConsume(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::gpss::StreamMessages>>(PrepareAsyncConsumeRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::gpss::StreamMessages>* ConsumeRaw(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request) override;
    ::grpc::ClientAsyncReader< ::gpss::StreamMessages>* AsyncConsumeRaw(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::gpss::StreamMessages>* PrepareAsyncConsumeRaw(::grpc::ClientContext* context, const ::gpss::ConsumeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Consume_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Consume(::grpc::ServerContext* context, const ::gpss::ConsumeRequest* request, ::grpc::ServerWriter< ::gpss::StreamMessages>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Consume() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* context, const ::gpss::ConsumeRequest* request, ::grpc::ServerWriter< ::gpss::StreamMessages>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsume(::grpc::ServerContext* context, ::gpss::ConsumeRequest* request, ::grpc::ServerAsyncWriter< ::gpss::StreamMessages>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Consume<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Consume() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* context, const ::gpss::ConsumeRequest* request, ::grpc::ServerWriter< ::gpss::StreamMessages>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Consume() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Consume(::grpc::ServerContext* context, const ::gpss::ConsumeRequest* request, ::grpc::ServerWriter< ::gpss::StreamMessages>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConsume(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Consume : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_Consume() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::gpss::ConsumeRequest, ::gpss::StreamMessages>(std::bind(&WithSplitStreamingMethod_Consume<BaseClass>::StreamedConsume, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_Consume() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Consume(::grpc::ServerContext* context, const ::gpss::ConsumeRequest* request, ::grpc::ServerWriter< ::gpss::StreamMessages>* writer) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedConsume(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::gpss::ConsumeRequest,::gpss::StreamMessages>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Consume<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Consume<Service > StreamedService;
};

}  // namespace gpss


#endif  // GRPC_stream_2eproto__INCLUDED
