// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gpss.proto

#include "gpss.pb.h"
#include "gpss.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace gpssfdw {

static const char* GpssFdw_method_names[] = {
  "/gpssfdw.GpssFdw/GetPages",
};

std::unique_ptr< GpssFdw::Stub> GpssFdw::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GpssFdw::Stub> stub(new GpssFdw::Stub(channel));
  return stub;
}

GpssFdw::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetPages_(GpssFdw_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GpssFdw::Stub::GetPages(::grpc::ClientContext* context, const ::gpssfdw::GetPagesRequest& request, ::gpssfdw::GetPagesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPages_, context, request, response);
}

void GpssFdw::Stub::experimental_async::GetPages(::grpc::ClientContext* context, const ::gpssfdw::GetPagesRequest* request, ::gpssfdw::GetPagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPages_, context, request, response, std::move(f));
}

void GpssFdw::Stub::experimental_async::GetPages(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gpssfdw::GetPagesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetPages_, context, request, response, std::move(f));
}

void GpssFdw::Stub::experimental_async::GetPages(::grpc::ClientContext* context, const ::gpssfdw::GetPagesRequest* request, ::gpssfdw::GetPagesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPages_, context, request, response, reactor);
}

void GpssFdw::Stub::experimental_async::GetPages(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gpssfdw::GetPagesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetPages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gpssfdw::GetPagesResponse>* GpssFdw::Stub::AsyncGetPagesRaw(::grpc::ClientContext* context, const ::gpssfdw::GetPagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gpssfdw::GetPagesResponse>::Create(channel_.get(), cq, rpcmethod_GetPages_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gpssfdw::GetPagesResponse>* GpssFdw::Stub::PrepareAsyncGetPagesRaw(::grpc::ClientContext* context, const ::gpssfdw::GetPagesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gpssfdw::GetPagesResponse>::Create(channel_.get(), cq, rpcmethod_GetPages_, context, request, false);
}

GpssFdw::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GpssFdw_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GpssFdw::Service, ::gpssfdw::GetPagesRequest, ::gpssfdw::GetPagesResponse>(
          std::mem_fn(&GpssFdw::Service::GetPages), this)));
}

GpssFdw::Service::~Service() {
}

::grpc::Status GpssFdw::Service::GetPages(::grpc::ServerContext* context, const ::gpssfdw::GetPagesRequest* request, ::gpssfdw::GetPagesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gpssfdw

